# config for development
version: 0.1
log:
  fields:
    service: registry
storage:
  hdfs:
    namenode: hadoop-master:9000
    rootdirectory: /tmp/
http:
  addr: :5000
  debug:
    addr: :5001
    prometheus:
      enabled: true
      path: /metrics
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
